name: Deploy App

on:
  push: #push時にactionsが実行される
  workflow_dispatch: #ワークフローを手動で実行できるイベント

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  test:
    name: test
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: npm run test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Setup Node.js and cache
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools

      - name: Write Firebase service account key (from base64)
        shell: bash
        run: |
          printf '%s' "${{ secrets.FIREBASE_KEY }}" | base64 -d > firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        run: ./node_modules/.bin/firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

      - name: Cleanup GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
        shell: bash
        run: |
          if [ -n "${GOOGLE_APPLICATION_CREDENTIALS:-}" ] && [ -e "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            rm -f -- "$GOOGLE_APPLICATION_CREDENTIALS"
          fi
